// Automatically generated by https://github.com/DualTachyon/rk3588-svd

/* Copyright 2024 Dual Tachyon
 * https://github.com/DualTachyon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */

#ifndef RK3588_UART2_H
#define RK3588_UART2_H

#include <stdint.h>

#include "uart/uart.h"

#define UART2_BASE                        0x0FEB50000U
#define UART2_SIZE                        0x000010000U
#define UART2                             ((volatile UART_t *)UART2_BASE)

#define UART2_ENUM_EQUALS(r, b, e)        (UART_##r##_GET_##b(UART2->r) == UART_##r##_##b##_VALUE_##e)
#define UART2_ENUM_BITS(r, b, e)          (UART_##r##_SET_##b(UART_##r##_##b##_VALUE_##e))
#define UART2_ENUM_BITS_WM(r, b, e)       (UART_##r##_SET_##b(UART_##r##_##b##_VALUE_##e) | (UART_##r##_##b##_MASK << 16))
#define UART2_ENUM_BITS_VALUE(r, b, v)    (UART_##r##_SET_##b(v))
#define UART2_ENUM_BITS_VALUE_WM(r, b, v) (UART_##r##_SET_##b(v) | (UART_##r##_##b##_MASK << 16))
#define UART2_ENUM_GET(r, b)              (UART_##r##_GET_##b(UART2->r))
#define UART2_ENUM_VALUE(r, b, e)         (UART_##r##_##b##_VALUE_##e)

#endif

